/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.Datos;
import java.io.StringWriter;
import Clases.XMLBase;
import java.awt.event.KeyEvent;
import java.io.StringReader;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import org.w3c.dom.Document;
import org.xml.sax.InputSource;

/**
 *
 * @author HiYeaismin 8a
 */
public class Vista_De_XMLBase extends javax.swing.JFrame {

    XMLBase contenido;

    /**
     * Creates new form Vista_De_XMLBase
     */
    public Vista_De_XMLBase() {
        initComponents();
        contenido = new XMLBase();
        this.setLocationRelativeTo(null);
        modeloDatos = (DefaultTableModel) tblDatos.getModel();
        btnBuscar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpopu = new javax.swing.JPopupMenu();
        GenerarXML = new javax.swing.JMenuItem();
        Eliminar = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        btnBuscar = new javax.swing.JButton();
        lblEscribir = new javax.swing.JLabel();
        txtEscribir = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        lblcaliz = new javax.swing.JLabel();

        GenerarXML.setText("GenerarXML");
        Jpopu.add(GenerarXML);

        Eliminar.setText("Eliminar");
        Jpopu.add(Eliminar);

        Buscar.setText("jMenuItem1");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        Jpopu.add(Buscar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblEscribir.setText("Escribir:");

        txtEscribir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEscribirKeyPressed(evt);
            }
        });

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datos:"
            }
        ));
        tblDatos.setComponentPopupMenu(Jpopu);
        jScrollPane1.setViewportView(tblDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEscribir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(lblcaliz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEscribir)
                    .addComponent(txtEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblcaliz, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEscribirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEscribirKeyPressed
        // TODO add your handling code here:
        //Escribir código para agregar datos al vector y mostrarlos a la tabla. Borrar el campo de texto.
        Datos dato = new Datos();
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                for (int iteracion = 0; iteracion < evt.getKeyCode(); iteracion++) {
                    dato.setDatos(txtEscribir.getText());
                    JOptionPane.showConfirmDialog(this, dato.getDatos());
                    //Guardarlo en el vector de XMLBase
                    boolean respuesta = contenido.insertar(dato, iteracion);
                    JOptionPane.showConfirmDialog(this, dato.getDatos());
                    // JOptionPane.showConfirmDialog(this, dato.getDatos());

                    modeloDatos.addRow(new Object[]{dato.getDatos()});
                    txtEscribir.setText("");
                }

            }
        } catch (NullPointerException error) {
            //JOptionPane.showMessageDialog(this, error);
        }

    }//GEN-LAST:event_txtEscribirKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        //Si hay datos en el modelo de la tabla. y en la tabla.
        try {
            int posicion = Integer.parseInt(txtEscribir.getText());
            Datos buscando = contenido.buscar(posicion);
            if (buscando == null) {
                JOptionPane.showMessageDialog(this, "No se pudo encontrar lo escrito.");
            } else {
                JOptionPane.showMessageDialog(this, buscando.getDatos());
                lblcaliz.setText(buscando.getDatos());
            }
        } catch (NullPointerException error) {

        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        btnBuscar.setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_De_XMLBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_De_XMLBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_De_XMLBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_De_XMLBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_De_XMLBase().setVisible(true);
            }
        });
    }
    DefaultTableModel modeloDatos;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem GenerarXML;
    private javax.swing.JPopupMenu Jpopu;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEscribir;
    private javax.swing.JLabel lblcaliz;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtEscribir;
    // End of variables declaration//GEN-END:variables
}
